version: '3.7'
services:
    mysql:
        container_name: annuel_mysql
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: annuel
            MYSQL_USER: annuel
            MYSQL_PASSWORD: annuel
        ports:
            - '3306'

    php:
        container_name: annuel_php
        build:
            context: ./.docker/php
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www/symfony_docker
        depends_on:
            - mysql

    nginx:
        container_name: annuel_nginx
        image: nginx:stable-alpine
        ports:
            - '8083:80'
        volumes:
            - .:/var/www/symfony_docker
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: annuel_phpmyadmin
        restart: always
        environment:
            PMA_HOST: annuel_mysql
            MYSQL_ROOT_PASSWORD: annuel
        depends_on:
            - mysql
        ports:
            - "8084:80"

volumes:
    annuel_mysql: